version: '3'

services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dev
    restart: always
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - '3000:3000'
